### ISSUE TITLE
ppm启动器的搜索与下载相关功能不可用

### ISSUE THREAD

**Issue by bzym2** [the-OmegaLabs/ppm#2]
- OS: Debian GNU/Linux 12
- Platform: x86_64
- Kernel: 6.1.0-25-amd64
- Shell: bash 5.2.15
- Desktop: GNOME
- PPM Version: Commit dc6d72a
#### BASH LOG
```bash
user@debian:~$ su
密码：
root@debian:/home/user# ppm init
<> 配置文件已初始化
root@debian:/home/user# ppm search wget
root@debian:/home/user# ppm download wget
```
ppm did not respond to my command, and I think this is a program error.

**Comment by Stevesuk0** [comment]
Try entering `ppm update` to download the repository list first.

**Comment by bzym2** [comment]
Solved:
Restart the client machine and open a new su bash, then enter `ppm update` to resolve the issue.
